import '../styles/globals.css';

import { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

// If loading a variable font, you don't need to specify the font weight
const openSans = Open_Sans({
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: 'Minimalist Resume',
  description: 'Generated by Next.js',
  icons: {
    shortcut: '/favicon.ico'
  },
  viewport: {
    width: 'device-width',
    initialScale: 1
  }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={openSans.className}>
      <body>{children}</body>
    </html>
  );
}
